services:
  app:
    build: .
    ports:
      - target: 1935        # Default streaming port
        published: 1935
      - target: 8087        # Wowza Streaming Engine API
        published: 8087
      - target: 8088        # Wowza Streaming Engine Manager UI
        published: 8088
      - target: 8089        # REST API documentation server (http://localhost:8089/api-docs)
        published: 8089
    environment:
      - CI=${CI}
      - WOWZA_LICENSE_KEY=${WOWZA_LICENSE_KEY}
      - WOWZA_MANAGER_USER=${WOWZA_MANAGER_USER}
      - WOWZA_MANAGER_PASSWORD=${WOWZA_MANAGER_PASSWORD}
      - WOWZA_ENABLE_DOCUMENTATION_SERVER=yes
    # Uncomment these when editing / running tests locally.
    # (Note: slows performance on macOS Catalina, for some reason.)
    # volumes:
    #   - ./test:/opt/app/test
    #   - ./artifacts:/opt/app/artifacts
